# Generated by Django 4.2.6 on 2023-12-05 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_bar_lateral_up', models.TextField(blank=True)),
                ('code_bar_lateral_down', models.TextField(blank=True)),
                ('code_bar_lateral_footer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='settings', max_length=255)),
                ('description_of_blog', models.TextField(default='In this blog I am going to talk about my daily routines.', max_length=300)),
                ('ico_image_therty_by_therty_px', models.ImageField(blank=True, null=True, upload_to='CustomizeBlog')),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='CustomizeBlog')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='CustomizeBlog')),
                ('background_color_head', models.CharField(default='Black', max_length=10)),
                ('background_color_bar_left', models.CharField(default='White', max_length=10)),
                ('background_color_bar_right', models.CharField(default='White', max_length=10)),
                ('background_color_footer', models.CharField(default='Black', max_length=10)),
                ('color_font_head', models.CharField(default='White', max_length=10)),
                ('color_font_bar_left', models.CharField(default='Black', max_length=10)),
                ('color_font_bar_right', models.CharField(default='Black', max_length=10)),
                ('color_font_footer', models.CharField(default='Black', max_length=10)),
            ],
            options={
                'verbose_name': 'Customize Blog',
            },
        ),
        migrations.CreateModel(
            name='PostArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_of_head', models.ImageField(blank=True, null=True, upload_to='PostArticle')),
                ('body', models.TextField()),
                ('show_views', models.BooleanField(default=True)),
                ('number_of_ping_backs', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('comment', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.postarticle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('reply', models.CharField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.postarticle')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.rating')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
