# Generated by Django 4.2.6 on 2023-12-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='value',
        ),
    ]
