# Generated by Django 4.2.6 on 2023-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_remove_reply_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
