# Generated by Django 4.2.6 on 2023-12-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_rename_comment_id_reply_comment_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='number_of_reply',
            field=models.IntegerField(default=0),
        ),
    ]
