# Generated by Django 4.2.6 on 2023-12-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_rating_number_of_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='show_comment_date',
            field=models.BooleanField(default=True),
        ),
    ]
