# Generated by Django 4.2.6 on 2023-12-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_postarticle_show_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postarticle',
            old_name='show_comment_date',
            new_name='show_comment_with_date',
        ),
    ]
