# Generated by Django 4.2.6 on 2024-03-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0007_rename_show_comment_date_postarticle_show_comment_with_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_message', models.CharField(max_length=400)),
                ('user_that_commented', models.CharField(max_length=200)),
                ('article_commented', models.CharField(max_length=200)),
                ('user_notified', models.CharField(max_length=200)),
                ('count_notification', models.IntegerField(default=0)),
                ('status_notification', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.postarticle')),
                ('rating_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.rating')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notify',
                'verbose_name_plural': 'notifies',
            },
        ),
    ]
