# Generated by Django 4.2.6 on 2024-03-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0008_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='user_id',
            new_name='user_notified_id',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='rating_id',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='user_notified',
        ),
    ]
