# Generated by Django 4.2.6 on 2024-03-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_rename_user_id_notify_user_notified_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='article_commented',
        ),
    ]
