# Generated by Django 4.2.6 on 2024-03-11 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0011_rename_user_notified_id_notify_user_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='user_notified',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notify',
            name='user_that_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
