# Generated by Django 4.2.6 on 2024-03-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0013_alter_notify_user_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='slug_image_user_that_commented',
            field=models.CharField(default='Nothing', max_length=200),
        ),
    ]
