# Generated by Django 4.2.6 on 2024-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0014_notify_slug_image_user_that_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
