# Generated by Django 4.2.6 on 2024-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0016_alter_postarticle_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postarticle',
            name='body',
            field=models.TextField(),
        ),
    ]
