# Generated by Django 4.2.6 on 2024-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0018_alter_postarticle_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeblog',
            name='active_setting',
            field=models.BooleanField(default=False),
        ),
    ]
