# Generated by Django 4.2.6 on 2024-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0019_customizeblog_active_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeblog',
            name='title_of_blog',
            field=models.CharField(default='Daily Routines', max_length=100),
        ),
    ]
