# Generated by Django 4.2.6 on 2024-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0020_customizeblog_title_of_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizeblog',
            name='notification_image',
            field=models.ImageField(blank=True, null=True, upload_to='CustomizeBlog'),
        ),
        migrations.AddField(
            model_name='customizeblog',
            name='profile_default_image',
            field=models.ImageField(blank=True, null=True, upload_to='CustomizeBlog'),
        ),
    ]
