# Generated by Django 4.2.6 on 2024-05-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0021_customizeblog_notification_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customizeblog',
            old_name='background_color_footer',
            new_name='background_color_head_footer',
        ),
        migrations.RemoveField(
            model_name='customizeblog',
            name='background_color_head',
        ),
    ]
