# Generated by Django 4.2.6 on 2024-05-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0022_rename_background_color_footer_customizeblog_background_color_head_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizeblog',
            name='background_color_bar_left',
        ),
        migrations.RemoveField(
            model_name='customizeblog',
            name='background_color_bar_right',
        ),
    ]
