from django.urls import path
from .views import  dologin, signup, PasswordsChangeView, UserUpdateView,ViewProfile, remove_user, senddata
from django.contrib.auth.views import PasswordResetView , PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,LogoutView

urlpatterns = [
    path('login/', dologin, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/',signup, name='register'),
    path('edit_profile',UserUpdateView.as_view(), name='edit_profile'),
    path('view_profile/<int:pk>',ViewProfile.as_view(), name='view_profile'),
    path('change_password/', PasswordsChangeView.as_view(), name='change_password'),
    path('delete_user/',remove_user, name='delete_user'),
    path('password_reset', PasswordResetView.as_view(
        template_name='pwd/password_reset.html'
    ), name='password_reset'),

    path('password_reset/done/', PasswordResetDoneView.as_view(
        template_name='pwd/password_reset_done.html'
    ), name='password_reset_done'),

    # PasswordResetConfirmView is generated by Django and it sends a confirmation email with a token
    # to the user email with a confirmation link.

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='pwd/password_reset_confirm.html'
    ), name='password_reset_confirm'),

    # PasswordResetCompleteView is generated by Django and it shows a template for reset completed.

    path('reset/done/', PasswordResetCompleteView.as_view(
        template_name='pwd/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('searching/', senddata, name='sent'),
]
